image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:

  PYFUNCEBLE_AUTO_CONFIGURATION: "YES"
  PYFUNCEBLE_CONFIG_DIR: "$CI_PROJECT_DIR/.pyfunceble"
  PYFUNCEBLE_OUTPUT_LOCATION: "$CI_PROJECT_DIR/.pyfunceble"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/


before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pyfunceble-dev

run:
  script:
    - PyFunceble --ci -f https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Phishing.Database/master/domains.list --ci-max-minutes 1
