# Python needed, so we use the python image.
image: python:latest

variables:
  # This is the Git name we have to set. (git config user.name)
  GIT_EMAIL: "pdns@pm.me"
  # This is the Git Email we have to set. (git config user.email)
  GIT_NAME: "My Privacy DNS"
  PYFUNCEBLE_AUTO_CONFIGURATION: "YES"
  PYFUNCEBLE_CONFIG_DIR: "$CI_PROJECT_DIR/.pyfunceble"
  PYFUNCEBLE_OUTPUT_LOCATION: "$CI_PROJECT_DIR/.pyfunceble"

before_script:
  # We install the development version of PyFunceble.
  # If you prefer the stable version replace `pyfunceble-dev`
  # with `pyfunceble`.
  - pip3 install PyFunceble mypdns

AdWare:
  stege: test
  script:
    # Let's say we want our results and our PyFunceble
    # infrastructure to be saved in a directory called `PyFunceble-tests`

    # We move inside it.
    - cd "$CI_PROJECT_DIR"
    - >
      pyfunceble --ci --syntax --no-files -f
      "$CI_PROJECT_DIR/source/adware/domains.list"
      "$CI_PROJECT_DIR/source/adware/wildcard.list"
