image: pyfunceble/pyfunceble:latest

# only:
#   - schedules

# before_script:
#   - echo "Before script section"
#   - echo "This is the pyfunceble test"
#   - echo "Or perhaps you might print out some debugging details"

# after_script:
#   - echo "After script section"
#   - echo "For example you might do some cleanup here"

build:
  stage: build
  script:
    - echo "1"
    - echo "2"
    - echo "3"
    - echo "4"
    - echo "5"
    - echo "6"
    - echo "7"
    - echo "8"
    - echo "9"
    - echo "10"
    # - docker container ls -a
    - docker run -it pyfunceble/pyfunceble --version
