# Python needed, so we use the python image.
image: python:latest

variables:
  PYFUNCEBLE_AUTO_CONFIGURATION: "YES"
  PYFUNCEBLE_CONFIG_DIR: "$CI_PROJECT_DIR/.pyfunceble"
  PYFUNCEBLE_OUTPUT_LOCATION: "$CI_PROJECT_DIR/.pyfunceble"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/


before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pyfunceble-dev mypdns

test1:
  stage: test
  script:
    # Let's say we want our results and our PyFunceble
    # infrastructure to be saved in a directory called `PyFunceble-tests`

    # We move inside it.
    - cd "$CI_PROJECT_DIR"
    - pyfunceble --ci --syntax --no-files -f "$CI_PROJECT_DIR/source/adware/domains.list" "$CI_PROJECT_DIR/source/adware/wildcard.list" --ci-max-minutes 5
